---
- name: Setup for nfs server
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Install nfs-kernel-server
      become: yes
      yum:
        name: nfs-kernel-server
        state: present
# file 모듈을 호출하여 NFS 공유 볼륨 디렉터리를 생성한다.
    - name: make nfs_shared directory
      file:
        path: /home/vagrant/nfs_shared
        state: directory
        mode: 0777


# 공유 볼륨 설정한다.
    - name: Create /etc/exports
      become: yes
      shell: "{{ item }}"
      with_items:
        - "touch /etc/exports"
        
    - name: configure /etc/exports
      become: yes
      lineinfile:
        path: /etc/exports
        line: /home/vagrant/nfs_shared 172.16.74.0/24(rw,sync)
      # blockinfile:
      #   path: /etc/exports
      #   block: /home/vagrant/nfs_shared 172.16.74.0/24(rw,sync)


# sudo 권한으로 서비스 재시작
    - name: nfs service restart
      become: yes
      service:
        name: nfs-kernel-server
        state: restarted


# 클라이언트 설정
- name: Setup for nfs clients
  hosts: all
  gather_facts: no

# file 모듈을 호출하여 NFS 공유 볼륨을 마운트할 디렉터리 생성
  tasks:
    - name: Install nfs-common
      become: yes
      yum:
        name: nfs-common
        state: present
        
    - name: make nfs_client directory
      file:
        path: /home/vagrant/nfs
        state: directory

# 마운트할 경로 지정과 마운트할 NFS 공유 볼륨 위치 지정
    - name: mount point directory as client
      become: yes
      mount:
        path: /home/vagrant/nfs
        src: 172.16.74.100:/home/vagrant/nfs_shared
        fstype: nfs
        opts: nfsvers=3
        state: mounted
# /etc/fstab에 추가
    - name: configure /etc/fstab
      become: yes
      lineinfile:
        path: /etc/fstab
        line: 172.16.74.100:/home/vagrant/nfs_shared /home/vagrant/nfs nfs defaults 0 0
