---
- name: Install nginx on the nodes
  hosts: nodes
  become: yes

  tasks:
    - name: install nginx web server for Ubuntu
      action: "{{ ansible_pkg_mgr }} name=nginx state=present update_cache=yes"
      when: ansible_distribution == "Ubuntu"