Description: "This template must run from Region that us-west-2 because that's Global accelerator."

Resources:
  Accelerator:
    Type: AWS::GlobalAccelerator::Accelerator
    Properties:
      Name: GA
      Tags:
        - Key: Name
          Value: GA

  Listener:
    Type: AWS::GlobalAccelerator::Listener
    Properties:
      AcceleratorArn: !Ref Accelerator
      Protocol: TCP
      PortRanges:
      - FromPort: 80
        ToPort: 80

  EndpointGroupSydney:
    Type: AWS::GlobalAccelerator::EndpointGroup
    Properties:
      ListenerArn: !Ref Listener
      EndpointGroupRegion: ap-southeast-2
      TrafficDialPercentage: 100
      EndpointConfigurations:
      - EndpointId: !Ref albArn
  EndpointGroupSao:
    Type: AWS::GlobalAccelerator::EndpointGroup
    Properties:
      ListenerArn: !Ref Listener
      EndpointGroupRegion: sa-east-1
      TrafficDialPercentage: 100
      EndpointConfigurations:
      - EndpointId: !Ref EndpointId1
      - EndpointId: !Ref EndpointId2
  # EndpointGroupSao2:
  #   Type: AWS::GlobalAccelerator::EndpointGroup
  #   Properties:
  #     ListenerArn: !Ref Listener
  #     EndpointGroupRegion: sa-east-1
  #     TrafficDialPercentage: 100
  #     EndpointConfigurations:
  #     - EndpointId: !Ref EndpointId2

Parameters:
  albArn: # arn:aws:elasticloadbalancing:ap-southeast-2:244516738903:loadbalancer/app/webserverALB/c95c775b36e299d2
    Type: String
    Description: "this region must be ap-southeast-2. The format must start arn."
    AllowedPattern: "arn:aws:elasticloadbalancing:.*"
  EndpointId1: # i-00bbe0e3b874106ce
    Type: String
    Description: "this region must be sa-east-1. The format must start 'i-' because that's instance ID."
  EndpointId2: # i-08ee5cb06a9671134
    Type: String
    Description: "this region must be sa-east-1. The format must start 'i-' because that's instance ID."

Outputs:
  StackAccelerator:
    Description: StackAccelerator
    Value: !Ref Accelerator
    Export:
      Name: StackAccelerator