Vagrant.configure("2") do |config|
    # httpd
    NODE_COUNT = 2
    NODE_COUNT.times do |i|
        config.vm.define "node0#{i+1}" do |cfg|
            cfg.vm.box = "starboard/ubuntu-arm64-20.04.5"
            cfg.vm.box_version = "20221120.20.40.0"
            cfg.vm.box_download_insecure = true
            cfg.vm.hostname = "node0#{i+1}"
            cfg.vm.network "private_network", ip: "172.16.74.10#{i+1}"
            # cfg.vm.network "forwarded_port", guest: 22, host: 60011, protocol: "tcp", auto_correct: true, id: "ssh"
            cfg.vm.synced_folder "../data", "/vagrant", disabled: true
            cfg.vm.provision "shell", inline: "apt update -y && apt install net-tools -y"
            cfg.vm.provider "vmware_desktop" do |v|
                v.ssh_info_public = true
                v.gui = true
                v.linked_clone = false
                # v.vmx["ethernet0.virtualdev"] = "vmxnet3"
                v.vmx["memsize"] = "1024"
                v.vmx["numvcpus"] = "2"
            end
        end
    end

    # nginx
    NODE_COUNT = 2
    NODE_COUNT.times do |i|
        config.vm.define "node1#{i+1}" do |cfg|
            cfg.vm.box = "starboard/ubuntu-arm64-20.04.5"
            cfg.vm.box_version = "20221120.20.40.0"
            cfg.vm.box_download_insecure = true
            cfg.vm.hostname = "node1#{i+1}"
            cfg.vm.network "private_network", ip: "172.16.74.11#{i+1}"
            # cfg.vm.network "forwarded_port", guest: 22, host: 60011, protocol: "tcp", auto_correct: true, id: "ssh"
            cfg.vm.synced_folder "../data", "/vagrant", disabled: true
            cfg.vm.provision "shell", inline: "apt update -y && apt install net-tools -y"
            cfg.vm.provider "vmware_desktop" do |v|
                v.ssh_info_public = true
                v.gui = true
                v.linked_clone = false
                # v.vmx["ethernet0.virtualdev"] = "vmxnet3"
                v.vmx["memsize"] = "1024"
                v.vmx["numvcpus"] = "2"
            end
        end
    end

    # Server
    config.vm.define "server" do |cfg|
        cfg.vm.box = "starboard/ubuntu-arm64-20.04.5"
        cfg.vm.box_version = "20221120.20.40.0"
        cfg.vm.box_download_insecure = true
        cfg.vm.hostname = "server"
        cfg.vm.network "private_network", ip: "172.16.74.100"
        # cfg.vm.network "forwarded_port", guest: 22, host: 60010, protocol: "tcp", auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true
        cfg.vm.provision "file", source: "ansible_default.yml", destination: "ansible_default.yml"
        cfg.vm.provision "shell", inline: "apt update -y && apt install net-tools ansible -y"
        cfg.vm.provision "shell", inline: "ansible-playbook ansible_default.yml"
        cfg.vm.provision "shell", path: "ssh_conf.sh"
        cfg.vm.provision "shell", path: "add_ssh_auth.sh"
        cfg.vm.provision "shell", inline: 'ssh-keygen -t rsa -f ~/.ssh/server -N ""'
        cfg.vm.provider "vmware_desktop" do |v|
            v.ssh_info_public = true
            v.gui = true
            v.linked_clone = false
            # v.vmx["ethernet0.virtualdev"] = "vmxnet3"
            v.vmx["memsize"] = "1024"
            v.vmx["numvcpus"] = "2"
        end
    end
end
