# -k 옵션 없이 사용 할 수 있게 함.
# Vagrantfile에서 ssh-keygen이 먼저 선행되어있다.
- name: Copy SSH public key to remote servers
  hosts: all
  gather_facts: no  # 노드 정보 모으기 안함
  become: yes
  tasks:
    - name: Copy SSH public key to remote servers
      authorized_key:
        user: vagrant
        key: "{{ lookup('file', '/home/vagrant/.ssh/server.pub') }}"