# SNS 생성
# AWS::SNS::Topic
# DisplayName
# AWS::SNS::Subscription
# Protocol: lambda
# TopicArn: !Ref 
# Endpoint: !Ref SecondUpdateLambdaArn

# 경보 생성
# AWS::CloudWatch::Alarm
# AWS/ApplicationELB
# HTTPCode_ELB_4XX_Count
# HTTPCode_ELB_5XX_Count
# TargetResponseTime

Parameters:
  ProjectName:
    Type: String
    Description: Here is Project Name. It will use to identifier.
    Default: Project1
  SecondUpdateLambdaArn:
    Type: String
    Description: Secondary Region Update Lambda Arn.
    Default: arn:aws:*
    AllowedPattern: arn:aws:*

Resources:
  ALBErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ALBErrorRateAlarm
      AlarmDescription: ALB Error Rate Alarm
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_ELB_4XX_Count  # 4XX 오류 카운트 모니터링 (오류 코드에 따라 조정 가능)
      Dimensions:
        - Name: LoadBalancer
          Value: YourLoadBalancerName  # 로드 밸런서 이름으로 변경
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 300  # 평가 주기 (초)
      Statistic: Sum
      Threshold: 5  # 5개 이상 오류 발생 시 경보
      AlarmActions:
        - !Ref SnsTopic  # 경보 발생 시 알림을 보낼 SNS 주제

  ALBLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ALBLatencyAlarm
      AlarmDescription: ALB Latency Alarm
      Namespace: AWS/ApplicationELB
      MetricName: TargetResponseTime  # 대상 응답 시간 모니터링
      Dimensions:
        - Name: LoadBalancer
          Value: YourLoadBalancerName  # 로드 밸런서 이름으로 변경
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Period: 300  # 평가 주기 (초)
      Statistic: Average
      Threshold: 5  # 5초 이상 응답 시간 경보
      AlarmActions:
        - !Ref SnsTopic  # 경보 발생 시 알림을 보낼 SNS 주제