Description: You must set from all region.

Resources:
  PubVPNRouteAWS1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableId
      DestinationCidrBlock: !Ref DestinationCidrBlock
      TransitGatewayId: !Ref mytgw

Parameters:
  DestinationCidrBlock:
    Description: "Here is DestinationCidrBlock."
    Type: String
  RouteTableId:
    Description: "Here is my route table id."
    Type: String
    AllowedPattern: "rtb-.*"
  mytgw:
    Description: "Here is my tgw id."
    Type: String
    AllowedPattern: "tgw-.*"