---
- name: Setup for the Ansible's Environment
  hosts: localhost

  tasks:
    - name: Create a VPC
      ec2_vpc_net:
        name: TEST  
        cidr_block: 10.10.0.0/16
        region: ap-northeast-2
