Resources:
  BASICVPC:
    Type: AWS::EC2::VPC
    Properties:
     CidrBlock: 192.168.0.0/16
     Tags:
        - Key: Name
          Value: BASIC-VPC

  BASICIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: BASIC-IGW

  BASICIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref BASICIGW
      VpcId: !Ref BASICVPC

  BASICPublicSN:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BASICVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 192.168.108.0/24
      Tags:
        - Key: Name
          Value: BASIC-Public-SN

  BASICPublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BASICVPC
      Tags:
        - Key: Name
          Value: BASIC-Public-RT

  BASICPublicSNRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BASICPublicRT
      SubBASIC: !Ref BASICPublicSN

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: BASICIGWAttachment
    Properties:
      RouteTableId: !Ref BASICPublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref BASICIGW

  BASICSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH, RDP
      VpcId: !Ref BASICVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0